on:
    push:
        branches:
            - main

permissions:
    id-token: write
    pages: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 8.0.x # Or your desired .NET version

            - name: Install DocFX
              run: |
                  dotnet tool install --global docfx
              shell: bash

            - name: Build DocFX
              run: |
                  docfx build docfx.json
              shell: bash

            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
              with:
                  artifact_name: "_site" # Or the name of your deployment folder
